### PR TITLE
Added WebSocket connection driver

### PR DESCRIPTION
**Pull request by v-zubko**

### CODE REVIEW

**Comment by v-zubko** [comment]
@winder Could you review my PR? Thanks.

**Comment by winder** [comment]
Could you revert the `package-lock.json` changes?

Other than that this looks good. What controller are you using with a websocket?

**Comment by v-zubko** [comment]
@winder Thank you for review. `package-lock.json` removed. 
> What controller are you using with a websocket?
If you ment WebSocket implementation then `org.glassfish.tyrus.bundles.tyrus-standalone-client`. Does it answer your question?

**Comment by winder** [comment]
Thanks @v-zubko, merged this in.

I was curious which controller you're using, like GRBL or TinyG. Do they run a server by default or did you have to setup something yourself?

**Comment by v-zubko** [comment]
I'm using GRBL on ESP07.

**Pull request merged**
