### PR TITLE
Added basic firmware setting support for TinyG controllers

### PR DESCRIPTION
**Pull request by breiler**
This will give basic firmware capabilities for tinyg controllers, part of #1071:
screenshot 2018-07-20 13 52 16

### CODE REVIEW

**Comment by breiler** [comment]
You mean changing like this?
```
firmware.tinyg.short.description.lv = Axis latch velocity
firmware.tinyg.short.description.lb = Axis latch backoff
firmware.tinyg.short.description.zb = Axis zero backoff
firmware.tinyg.short.description.ma = Motor map to axis
firmware.tinyg.short.description.sa = Motor step angle
```

**Comment by winder** [comment]
I was thinking more dynamic, like "Axis 1" or "Motor 2"

**Comment by breiler** [comment]
Good idea, I'll see what I can do.

**Comment by breiler** [comment]
Added the setting group as a prefix to the setting. I decided to make them fully translatable using the key: `firmware.tinyg.group.description.<group name>`. I figured that this will be the best in the long run because there are many types of setting groups and we don't know how they should be displayed:

https://github.com/synthetos/TinyG/wiki/TinyG-Configuration-for-Firmware-Version-0.97#motor-groups

New example:
screenshot 2018-07-21 13 23 07

**Comment by winder** [comment]
Looks fantastic!

**Comment by justinclift** [comment]
Only had time to have a quick go with this today, as other stuff came up.  For me, the firmware settings page shows fine, though I didn't try changing anything (needed to get stuff cut).  Actual UGS operation went fine too (cutting another one of those brackets).

So far, so good. :smile:

**Pull request merged**
