### PR TITLE
Synchronize localization.

### PR DESCRIPTION
**Pull request by winder**
* Push keys to POEditor
* Download latest updates from POEditor
* Add Serbian and zh-Hans to `AvailableLanguages.java`
    * Question: we have localizations for zh-CN and zh-Hans, POEditor calls them Chinese and Simplified Chinese but the [Oracle International Language Environment Guide](https://docs.oracle.com/cd/E23824_01/html/E26033/glset.html) does not have `zh-Hans`. Can anyone recommend the correct name for these two localizations?
* Rename mappings and resource files to match recent locale fixes.

### CODE REVIEW

**Comment by breiler** [comment]
Hi Will,

I took the liberty to register the project to Crowdin and we got a free open source license: https://translate.universalgcodesender.com/

Crowdin has a direct Github integration and creates pull requests when someone edits translations. It also has other nice features such as support for uploading screenshots to add  context for a translation string. Overall I felt that Crowdin has more features that simplifies the translation.

I looked through the translations for zh-CN and zh-Hans and the translations looked very similar on many places. And according to the Java documentation and Crowdin the zh-CN is Chinese simplified. It is possible that I've messed this up, so if someone has more insights I'd be happy to correct!

If you rather use POEditor I can revert my changes. But the way it needs to be renewed I felt that I would like to move on. =)

**Comment by winder** [comment]
Neat! The screenshot feature sounds really useful and proper GitHub integration would be great. We also have an open source license for POEditor. When I was evaluating the tools originally the GH integrations were all pretty bad, POEditor edged out the rest with a decent API.

I don't have a strong opinion about switching to another service, but I'll offer some things to consider:
* POEditor has 151 contributors.
* The docs are setup to send people to POEditor.
* The POEditor was marked "archived" because I hadn't logged into it for so long.
* The POEditor terms are always out of date because I manually run the `update_languages.py` script.
* It looks like POEditor has improved the GH integration. It still looks pretty basic, I can't vouch for it.

I just added you as an admin to POEditor if you want to click around the site

**Comment by winder** [comment]
Looks like only 6 languages have been updated on POEditor in the last year, so the 151 number is not quite as impressive as it seemed.

**Comment by breiler** [comment]
I was not allowed to see or change the Github integration changes. We can keep the poeditor as it has a bit cleaner and more user friendly interface. I'll revert my changes for crowdin once this is merged

**Review by breiler — APPROVED** [review]

**Comment by breiler** [comment]
I merged the content of this PR with the translations made in Crowdin, closing this.

**Pull request closed without merging**
