### PR TITLE
Add action for following the running gcode in the editor

### PR DESCRIPTION
**Pull request by breiler**
It will select the line that was last completed by the controller when using the toggle button in the editor.

### CODE REVIEW

**Comment by chrisla23** [comment]
Given that this is worked out, could this line info be added to a popup
when it goes into an alarm state?

Thanks,

-Chris

**Comment by breiler** [comment]
@hrenz it should be available here in version 2.0.14 or later:
image

This feature is completely new, did not want to turn it on by default as I don't know if it has performance implications.

**Comment by hrenz** [comment]
no, no field no button

**Comment by breiler** [comment]
> 2.0.14 or later

You are running 2.0.12, dude please stop wasting my time...

**Comment by hrenz** [comment]
sorry now its 2.0.14

**Pull request merged**
