### PR TITLE
Automatically connect when cnc is found

### PR DESCRIPTION
**Pull request by philreindl**
#336 - Autoconnect to cnc.  If connection is lost, clean up the connection.

The behavior is the same as though the open/close button has been pressed.

### CODE REVIEW

**Comment by philreindl** [comment]
Still need to add the gui change for managing the setting

**Comment by philreindl** [comment]
GUI for managing settings is in place, should be good to go.

**Comment by winder** [comment]
Looks good @philreindl, one thing I wonder that you might have tried out. Are all the default value in SettingsFactory.java obsolete now? It seems like the default member value in Settings.java will do that job now (which is what you're levereging here?).

**Comment by philreindl** [comment]
Looks like the SettingsFactory defaults only matter when the file being loaded is the old .properties version.  If we wanted to get rid of the defaults in there, we'd want to test that the property exists before getting its value.  IMO, that code should be left alone until support for the old .properties file is dropped.  

Another approach might be to have the Settings class just be a container for a bunch of Setting objects.  Each Setting would be an entry in the enum, which would be a single place to define default value, name (i8n code), etc.   A project for a different day.

**Comment by philreindl** [comment]
oops didn't mean to close.

**Pull request merged**
