### PR TITLE
add a wait loop to prevent the 'job complete' popup until all active commands complete

### PR DESCRIPTION
**Pull request by bryanduxbury**
Untested, but wanted to get your sense of whether this is an approximately OK way to go. 

Also, is master build broken right now? I'm getting some compile errors in GUIBackend.java about missing members:

```
-do-compile:
    [mkdir] Created dir: /Users/duxbury/Development/personal/Universal-G-Code-Sender/build/empty
    [mkdir] Created dir: /Users/duxbury/Development/personal/Universal-G-Code-Sender/build/generated-sources/ap-source-output
    [javac] Compiling 60 source files to /Users/duxbury/Development/personal/Universal-G-Code-Sender/build/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] /Users/duxbury/Development/personal/Universal-G-Code-Sender/src/com/willwinder/universalgcodesender/model/GUIBackend.java:147: error: cannot find symbol
    [javac]         systemStateBean.setMachineX(Utils.formatter.format(this.machineCoord.getX()));
    [javac]                                                                             ^
    [javac]   symbol:   method getX()
    [javac]   location: variable machineCoord of type Point3d
    [javac] /Users/duxbury/Development/personal/Universal-G-Code-Sender/src/com/willwinder/universalgcodesender/model/GUIBackend.java:148: error: cannot find symbol
    [javac]         systemStateBean.setMachineY(Utils.formatter.format(this.machineCoord.getY()));
    [javac]                                                                             ^
    [javac]   symbol:   method getY()
    [javac]   location: variable machineCoord of type Point3d
    [javac] /Users/duxbury/Development/personal/Universal-G-Code-Sender/src/com/willwinder/universalgcodesender/model/GUIBackend.java:149: error: cannot find symbol
    [javac]         systemStateBean.setMachineZ(Utils.formatter.format(this.machineCoord.getZ()));
    [javac]                                                                             ^
    [javac]   symbol:   method getZ()
    [javac]   location: variable machineCoord of type Point3d
    [javac] /Users/duxbury/Development/personal/Universal-G-Code-Sender/src/com/willwinder/universalgcodesender/model/GUIBackend.java:153: error: cannot find symbol
    [javac]         systemStateBean.setWorkX(Utils.formatter.format(this.workCoord.getX()));
    [javac]                                                                       ^
    [javac]   symbol:   method getX()
    [javac]   location: variable workCoord of type Point3d
    [javac] /Users/duxbury/Development/personal/Universal-G-Code-Sender/src/com/willwinder/universalgcodesender/model/GUIBackend.java:154: error: cannot find symbol
    [javac]         systemStateBean.setWorkY(Utils.formatter.format(this.workCoord.getY()));
    [javac]                                                                       ^
    [javac]   symbol:   method getY()
    [javac]   location: variable workCoord of type Point3d
    [javac] /Users/duxbury/Development/personal/Universal-G-Code-Sender/src/com/willwinder/universalgcodesender/model/GUIBackend.java:155: error: cannot find symbol
    [javac]         systemStateBean.setWorkZ(Utils.formatter.format(this.workCoord.getZ()));
    [javac]                                                                       ^
    [javac]   symbol:   method getZ()
    [javac]   location: variable workCoord of type Point3d
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 6 errors
    [javac] 1 warning
```

### CODE REVIEW

**Comment by winder** [comment]
The code should be alright, it looks like the vecmath.jar library isn't being found in your build.

Since this code is triggered by a serial event, I don't think you can have a blocking loop here.  Also the fileStreamComplete event already waits for the awaitingResponseQueue size to be zero:
https://github.com/bryanduxbury/Universal-G-Code-Sender/blob/wait-for-finish/src/com/willwinder/universalgcodesender/AbstractController.java#L689

**Comment by bryanduxbury** [comment]
Hm, I hadn't noticed that section in AbstractController earlier. If I follow correctly, before the fileStreamComplete callbacks are triggered, the awaitingResponseQueue should be empty. However, anecdotally, that's not the case when I'm running my machine. I get the "Job Complete" popup before the final cuts of the job are done moving.

Is it possible there's a concurrency issue here? Are commands being drained from the awaiting queues in one thread while this thread is checking for completeness? (Sorry for the basic questions, I'm still getting up to speed on the codebase.)

**Comment by winder** [comment]
I think part of the problem here is that UGS is counting the "OK" that GRBL sends and that GRBL may say send the "OK" before the command has completed. This is especially noticable if the last command is a really long movement.

**Comment by winder** [comment]
I think this should be resolved with some changes I made recently.

**Pull request closed without merging**
