### PR TITLE
Feature/tinyg

### PR DESCRIPTION
**Pull request by breiler**
Started improving the support for TinyG/g2core (#1071). I've tested this with g2core version 100.26 found here: https://github.com/synthetos/g2

* It works to send file, pause and stop
* Machine coordinates are reported
* GCode states are handled
* Status reports interval are enabled
* Jogging works (also continous)

There are still a lot of unit tests to be written and features missing. But I'm hoping to get feedback from the TinyG- and g2core community.

### CODE REVIEW

**Comment by breiler** [comment]
I've been testing and found some small stuff, but I think it's as ready as it can get at the moment. How do you feel about me merging this?

**Comment by breiler** [comment]
@justinclift if it gets merged it will automatically build and be available in the nightly builds. The download links can be found on the project page https://github.com/winder/Universal-G-Code-Sender#downloads and on the web page http://winder.github.io/ugs_website/download/#nightly-builds

I'm hoping that I can get some help verifying that it's working from the g2core community. There is still some features that I would like to have in place such as: homing, work coordinates and settings. And of course test on more devices and versions before I dare to say it's working. =P

**Comment by justinclift** [comment]
Makes sense to me.  We haven't yet established strong channels for reaching out to contributors, so it's kind of tricky atm to put out a "call for action" and get a useful response. :frowning_face: 

(yeah, we need to improve on this)

That being said, we can definitely ask in some of the known places that TinyG and g2core people frequent and see if useful responses turn up.  I'll also give it a go with my personal gear (a Shapeoko3 with Arduino Due + home made stepper board) to hopefully shake out any early stages gotchas. :smile:

**Comment by justinclift** [comment]
Cool.  I'll give this a shot sometime tomorrow, and see if any strangeness turns up.  I'll also have a go with our more experimental edge branch builds, to see if that works ok without modification too.  We've been changing some stuff in there. :innocent:

**Comment by justinclift** [comment]
@rkoe @yck011522 @msepulve @shczm @scotthz Any interest in trying out a nightly build of Universal G-Code Sender with g2core?

Tentative working support for g2core (build 100.26) has just been merged, and should be included in tomorrow's nightly builds:

&nbsp; &nbsp; https://github.com/winder/Universal-G-Code-Sender#downloads

As it's newly added stuff, all reports of success/failure/weirdness (etc) are likely really helpful. :smile:

**Comment by scotthz** [comment]
@justinclift Sure, this could be interesting. Sorry to take so long to respond. I am currently running build 101.03 though. As long as that wouldn't be a **known** problem, I'll go ahead and give UGS a shot.

**Comment by justinclift** [comment]
@scotthz No worries at all.  I was away all weekend myself, so just catching up with things now.

It turns out there's an overall tracking issue for this already, in #1071.  I'll continue with the details there. :smile:

**Comment by justinclift** [comment]
@breiler Just a heads up, the breiler.com domain name appears to have expired.  Emails to you are timing out with hard/non-recoverable errors.

**Pull request merged**
